/*
 * Copyright 2005-2026 Hyland Software, Inc. and its affiliates. All rights reserved.
 * License rights for this program may be obtained from Hyland Software, Inc. and its affiliates.
 * pursuant to a written agreement and any use of this program without such an
 * agreement is prohibited.
 */

import { UnitTestRunner } from '@nx/angular/generators';
import { ProjectConfiguration, Tree, readProjectConfiguration, updateProjectConfiguration, joinPathFragments } from '@nx/devkit';
import { NormalizedSchema } from '../models/normalized-schema';
import { TestConfiguration } from '../models/test-configuration';
import { isComponentLibrary } from '../models/library-types';

export function editLibraryProjectJson(tree: Tree, options: NormalizedSchema) {
    const currentProjectConfig = readProjectConfiguration(tree, options.projectName);
    const testConfiguration = options.unitTestRunner === UnitTestRunner.Jest ? getJestConfiguration() : {};
    const { targets } = currentProjectConfig;

    // Remove lint target as we use inferred tasks
    delete targets['lint'];

    if (isComponentLibrary(options.type)) {
        targets['stylelint'] = {};
    }

    if (options.buildable && targets['build']) {
        targets['build'] = {
            ...targets['build'],
            configurations: {
                production: {
                    tsConfig: '{projectRoot}/tsconfig.lib.prod.json',
                },
                development: {
                    tsConfig: '{projectRoot}/tsconfig.lib.json',
                },
                adf: {
                    tsConfig: '{projectRoot}/tsconfig.lib.adf.json',
                },
            },
        };
    } else if (!options.buildable) {
        delete targets['build'];
    }

    const tags = generateTags(options);

    const project: ProjectConfiguration & { prefix: string } = {
        ...currentProjectConfig,
        prefix: options.prefix,
        targets: { ...targets, ...testConfiguration },
        tags,
    };

    updateProjectConfiguration(tree, options.projectName, project);
    removeAutogeneratedTargetsComment(tree, project);

    return project;
}

function generateTags(options: NormalizedSchema): string[] {
    const tags = [`scope:${options.projectName}`, `type:${options.type}`, `category:${options.category}`];

    if (options.externalWorkstreamScope?.trim() && options.externalWorkstreamScope !== 'none') {
        tags.push(`scope:${options.externalWorkstreamScope.trim()}`);
    }

    return tags;
}

function removeAutogeneratedTargetsComment(tree: Tree, project: ProjectConfiguration): void {
    const autogeneratedCommentedTargetsPropertyKey = '// targets';
    const projectJsonPath = joinPathFragments(project.root, 'project.json');
    const projectJsonContent = tree.read(projectJsonPath, 'utf-8');

    if (projectJsonContent) {
        const projectJson = JSON.parse(projectJsonContent);
        if (projectJson[autogeneratedCommentedTargetsPropertyKey]) {
            delete projectJson[autogeneratedCommentedTargetsPropertyKey];
            tree.write(projectJsonPath, JSON.stringify(projectJson, null, 4) + '\n');
        }
    }
}

function getJestConfiguration(): TestConfiguration {
    return {
        test: {
            executor: '@nx/jest:jest',
            options: {
                jestConfig: '{projectRoot}/jest.config.ts',
                passWithNoTests: true,
            },
            configurations: {
                adf: {
                    jestConfig: '{projectRoot}/jest.adf.config.ts',
                    codeCoverage: false,
                    silent: true,
                },
            },
        },
    };
}
